defmodule LearnElixir.Math.Plan do
  @moduledoc "Structured output for math prompts, generated by Instructor or the local fallback."

  use Ecto.Schema
  use Instructor.Validator

  import Ecto.Changeset

  alias LearnElixir.Math.Step

  @primary_key false
  @doc """
  A structured, verifiable math response.

  ## Fields
  - problem: the original prompt from the user.
  - normalized_expression: a safe arithmetic expression using +, -, *, /, and **.
  - final_answer: the numeric result of the expression.
  - answer_unit: an optional unit label.
  - confidence: a score between 0.0 and 1.0.
  - steps: ordered reasoning steps explaining how the answer was produced.
  """
  embedded_schema do
    field(:problem, :string)
    field(:normalized_expression, :string)
    field(:final_answer, :float)
    field(:answer_unit, :string)
    field(:confidence, :float)
    embeds_many(:steps, Step)
  end

  @impl true
  def validate_changeset(changeset) do
    changeset
    |> validate_required([:problem, :normalized_expression, :final_answer, :confidence])
    |> validate_length(:problem, min: 3)
    |> validate_length(:normalized_expression, min: 1)
    |> validate_number(:confidence, greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.0)
    |> validate_change(:steps, &validate_steps/2)
    |> validate_change(:normalized_expression, &validate_expression/2)
  end

  def new(attrs) do
    changeset =
      %__MODULE__{}
      |> cast(attrs, [:problem, :normalized_expression, :final_answer, :answer_unit, :confidence])
      |> cast_embed(:steps, with: &Step.changeset/2, required: true)
      |> validate_changeset()

    case apply_action(changeset, :insert) do
      {:ok, plan} -> {:ok, plan}
      {:error, changeset} -> {:error, changeset}
    end
  end

  def format_answer(%__MODULE__{final_answer: answer, answer_unit: nil}),
    do: format_number(answer)

  def format_answer(%__MODULE__{final_answer: answer, answer_unit: unit}) do
    "#{format_number(answer)} #{unit}"
  end

  defp validate_steps(:steps, steps) when is_list(steps) do
    if length(steps) < 2 do
      [steps: "should contain at least two reasoning steps"]
    else
      []
    end
  end

  defp validate_steps(:steps, _steps), do: [steps: "must be a list of structured steps"]

  defp validate_expression(:normalized_expression, expression) when is_binary(expression) do
    allowed? = Regex.match?(~r/\A[\d\.\+\-\*\/\(\)\s]+\z/, expression)

    if allowed? do
      []
    else
      [normalized_expression: "contains unsupported characters"]
    end
  end

  defp validate_expression(:normalized_expression, _expression),
    do: [normalized_expression: "must be a string"]

  defp format_number(number) when is_number(number) do
    rounded = Float.round(number * 1.0, 6)

    if rounded == trunc(rounded) do
      Integer.to_string(trunc(rounded))
    else
      :erlang.float_to_binary(rounded, decimals: 6)
      |> String.trim_trailing("0")
      |> String.trim_trailing(".")
    end
  end
end
